Feature/vrvu-71: Add Box for adding estimated Age
johnsonandjohnson/vxnaid pull request #47
Opened 2024-07-17 14:13 UTC by sherrif10

PR here   https://sd-vxnaid.atlassian.net/browse/VRVU-71   cc @jdolkowski  @druchniewicz 

This is basically a box for adding estimated age.
![Screenshot 2024-07-17 140614](https://github.com/user-attachments/assets/01b274e4-74dd-45e3-b6bb-629eab259660)

2024-07-18 09:22 UTC, druchniewicz requested changes

2024-07-18 09:22 UTC, druchniewicz commented on app/src/main/java/com/jnj/vaccinetracker/register/dialogs/BirthDatePickerDialog.kt
> +                            numberPickerYears.value = estimatedAge
how does it work? how does it affect the date?
for example estimatedAge = 5 and 5 is assigned to year picker or do I understand wrong?

2024-07-18 09:22 UTC, druchniewicz commented on app/src/main/java/com/jnj/vaccinetracker/register/dialogs/BirthDatePickerDialog.kt
> +            val month = c.get(Calendar.MONTH)
why it is changed?

2024-07-18 09:57 UTC, sherrif10 commented on app/src/main/java/com/jnj/vaccinetracker/register/dialogs/BirthDatePickerDialog.kt
> +            val month = c.get(Calendar.MONTH)
i will revert this. Thanks

2024-07-18 09:57 UTC, sherrif10 commented on app/src/main/java/com/jnj/vaccinetracker/register/dialogs/BirthDatePickerDialog.kt
> +                            numberPickerYears.value = estimatedAge
ideally estimated Age should be assigned to the age value. as simple as that. Could you try to give me how you would implement this ?

2024-07-18 11:31 UTC, druchniewicz commented on app/src/main/java/com/jnj/vaccinetracker/register/dialogs/BirthDatePickerDialog.kt
> +                            numberPickerYears.value = estimatedAge
we don't have field in database for age. I would go with solution when estimated age is entered/changed then year picker is automatically set to correct year, e.g. we have now 2024, when we enter estimated age e.g. to 7 years, then year picker is automatically set to 2017 and this date is saved in database

2024-07-18 11:51 UTC, sherrif10 commented on app/src/main/java/com/jnj/vaccinetracker/register/dialogs/BirthDatePickerDialog.kt
> +                            numberPickerYears.value = estimatedAge
This Makes sense. , Let me implement that kind of logic then .

2024-07-18 13:13 UTC, jdolkowski commented
I think we should take a different approach here. The popup should remain unchanged. If date is estimated birth date should display calculated age instead of a date. cc @sherrif10

2024-07-18 20:00 UTC, sherrif10 commented
Okay i get, i will try to fix it.

2024-07-24 03:41 UTC, sherrif10 commented
Closing this, i will open a new PR

2024-07-24 03:41 UTC, closed without merging